# Generated by Django 3.2.5 on 2022-01-30 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_name', models.CharField(max_length=200)),
                ('banner_type', models.CharField(choices=[('banner1', 'Side-Banner'), ('banner-two', 'Top-Banner')], max_length=200)),
                ('activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200)),
                ('site_logo', models.ImageField(upload_to='sites/images')),
                ('bottom_logo', models.ImageField(upload_to='site/images')),
                ('favicon', models.ImageField(upload_to='site/images')),
                ('meta_tag_keywords', models.CharField(blank=True, max_length=512, null=True)),
                ('meta_tag_discription', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('about', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAdsense',
            fields=[
                ('addsense_id', models.AutoField(primary_key=True, serialize=False)),
                ('addsense_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('analtical_id', models.AutoField(primary_key=True, serialize=False)),
                ('analytics_tag', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_owner', models.CharField(max_length=50)),
                ('business_address', django_quill.fields.QuillField()),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscribers',
            fields=[
                ('subscriber_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=100, unique=True)),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(max_length=100)),
                ('wattsapp_link', models.URLField(max_length=100)),
                ('twitter_link', models.URLField(max_length=100)),
                ('youtube_link', models.URLField(max_length=100)),
                ('telegram_link', models.URLField(max_length=100)),
                ('twitter_handle', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_image1', models.ImageField(upload_to='site/banners')),
                ('banner_image2', models.ImageField(upload_to='site/banners')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bannner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesetting.banner')),
            ],
        ),
    ]
