# Generated by Django 3.2.5 on 2022-03-08 10:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_name', models.CharField(max_length=200, unique=True)),
                ('activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_address', django_quill.fields.QuillField()),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='site/ads/images')),
                ('active', models.BooleanField(default=True)),
                ('target_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, unique=True)),
                ('site_logo', models.ImageField(upload_to='sites/images')),
                ('bottom_logo', models.ImageField(upload_to='site/images')),
                ('favicon', models.ImageField(upload_to='site/images')),
                ('meta_tag_keywords', models.CharField(blank=True, max_length=512, null=True)),
                ('meta_tag_discription', models.TextField(blank=True, max_length=200, null=True)),
                ('analytics_tag', models.TextField(blank=True, null=True)),
                ('adsense_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=100, unique=True)),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscribers',
            fields=[
                ('subscriber_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaFeedType',
            fields=[
                ('feed_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('icon', models.ImageField(null=True, upload_to='site/images')),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesetting.socialmediafeedtype')),
            ],
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_image', models.ImageField(upload_to='site/banners')),
                ('image_ref_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bannner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitesetting.banner')),
            ],
        ),
    ]
