# Generated by Django 3.2.5 on 2022-02-03 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedialinks',
            old_name='facebook_link',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='wattsapp_link',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='fav_icon',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='platform_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
