# Generated by Django 3.2.5 on 2022-02-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0002_auto_20220203_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='fav_icon',
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='icon',
            field=models.ImageField(null=True, upload_to='site/images'),
        ),
    ]
