# Generated by Django 3.2.5 on 2022-02-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0003_auto_20220203_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimages',
            name='banner_image2',
        ),
    ]
