# Generated by Django 3.2.5 on 2022-02-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0004_remove_bannerimages_banner_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('banner1', 'Side-Banner'), ('banner-two', 'Main-Page-Banner'), ('banner-three', 'Game-Page-Banner'), ('banner-four', 'Blog-Page-Banner'), ('banner-five', 'Kids-Page-Banner')], max_length=200),
        ),
    ]
