# Generated by Django 3.2.5 on 2022-02-27 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0006_alter_banner_banner_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAdsense',
        ),
        migrations.DeleteModel(
            name='GoogleAnalytics',
        ),
        migrations.RemoveField(
            model_name='general',
            name='about',
        ),
        migrations.AddField(
            model_name='general',
            name='adsense_code',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='general',
            name='analytics_tag',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
