# Generated by Django 3.2.5 on 2022-02-27 11:00

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0007_auto_20220227_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Link_name', models.CharField(max_length=100, unique=True)),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.DeleteModel(
            name='Policies',
        ),
        migrations.RenameField(
            model_name='bannerimages',
            old_name='banner_image1',
            new_name='banner_image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner_type',
        ),
        migrations.AddField(
            model_name='bannerimages',
            name='image_ref_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='adsense_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='analytics_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
