# Generated by Django 3.2.5 on 2022-03-01 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0009_customadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customadvertisement',
            name='target_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
