# Generated by Django 3.2.5 on 2022-03-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0010_customadvertisement_target_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customadvertisement',
            name='icon',
        ),
        migrations.AddField(
            model_name='customadvertisement',
            name='image',
            field=models.ImageField(null=True, upload_to='site/ads/images'),
        ),
    ]
