# Generated by Django 3.2.5 on 2022-03-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetting', '0013_auto_20220303_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantlink',
            old_name='Link_name',
            new_name='link_name',
        ),
    ]
