# Generated by Django 3.2.5 on 2022-03-08 10:01

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidsContentType',
            fields=[
                ('content_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreCatagory',
            fields=[
                ('store_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_thumbnail', models.ImageField(upload_to='kidstore/image/thumbnail')),
                ('content_cover', models.ImageField(upload_to='kidstore/images/cover')),
                ('content_title', models.CharField(max_length=100)),
                ('content_content', django_quill.fields.QuillField()),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidstore.kidscontenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AffilatedProducts',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_embed_type', models.CharField(choices=[('url-embed', 'URL-Embed'), ('html-embed', 'HTML-Embed')], max_length=100)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('product_embeded_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kidstore.storecatagory')),
            ],
        ),
    ]
