# Generated by Django 3.2.5 on 2022-02-16 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kidstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='story_id',
            new_name='content_id',
        ),
        migrations.AddField(
            model_name='affilatedproducts',
            name='product_embed_type',
            field=models.CharField(choices=[('url-embed', 'URL-Embed'), ('html-embed', 'HTML-Embed')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='affilatedproducts',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affilatedproducts',
            name='product_embeded_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
