# Generated by Django 3.2.5 on 2022-02-18 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kidstore', '0002_auto_20220216_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='kidstore/images/cover'),
            preserve_default=False,
        ),
    ]
