# Generated by Django 3.2.5 on 2022-02-18 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kidstore', '0003_content_content_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='kidstore/images/cover'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='content_thumbnail',
            field=models.ImageField(height_field='300', upload_to='kidstore/image/thumbnail', width_field='300'),
        ),
    ]
