# Generated by Django 3.2.5 on 2022-02-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidstore', '0004_auto_20220218_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_thumbnail',
            field=models.ImageField(upload_to='kidstore/image/thumbnail'),
        ),
    ]
