# Generated by Django 3.2.5 on 2022-01-30 12:33

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCatagory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSubCategory',
            fields=[
                ('sub_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_cat_name', models.CharField(max_length=200)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogcatagory')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_content', django_quill.fields.QuillField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogcatagory')),
                ('blog_sub_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogsubcategory')),
            ],
        ),
    ]
