# Generated by Django 3.2.5 on 2022-02-11 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='active',
        ),
        migrations.AddField(
            model_name='blog',
            name='background_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='/blogs/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='tendiing',
            field=models.BooleanField(default=True),
        ),
    ]
