# Generated by Django 3.2.5 on 2022-02-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20220211_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='background_img',
            field=models.ImageField(upload_to='blogs/images'),
        ),
    ]
