# Generated by Django 3.2.5 on 2022-02-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_background_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tendiing',
            new_name='trending',
        ),
    ]
