# Generated by Django 3.2.5 on 2022-02-15 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_tendiing_blog_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_cover_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blogs/images/cover'),
            preserve_default=False,
        ),
    ]
