# Generated by Django 3.2.5 on 2022-03-08 10:01

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=250, unique=True)),
                ('game_description', django_quill.fields.QuillField()),
                ('play_link', models.URLField()),
                ('game_landing_page_link', models.URLField()),
                ('game_cover', models.ImageField(upload_to='games/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameUpdateType',
            fields=[
                ('update_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_type_name', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
            ],
        ),
        migrations.CreateModel(
            name='GameUpdates',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('update_title', models.CharField(max_length=200)),
                ('update_description', django_quill.fields.QuillField()),
                ('update_link', models.URLField(blank=True, null=True)),
                ('update_thumbnail', models.ImageField(upload_to='games/update/images')),
                ('update_cover', models.ImageField(upload_to='games/update/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games')),
                ('update_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameupdatetype')),
            ],
        ),
    ]
