# Generated by Django 3.2.5 on 2022-02-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameupdatetype_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameupdates',
            old_name='update_banner_one',
            new_name='update_cover',
        ),
        migrations.RenameField(
            model_name='gameupdates',
            old_name='update_banner_two',
            new_name='update_thumbnail',
        ),
    ]
