# Generated by Django 3.2.5 on 2022-02-20 13:18

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220219_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameupdates',
            name='update_description',
            field=django_quill.fields.QuillField(),
        ),
    ]
