# Generated by Django 3.2.5 on 2022-02-20 14:13

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gameupdates_update_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='banner_one',
            new_name='game_cover',
        ),
        migrations.RemoveField(
            model_name='games',
            name='banner_two',
        ),
        migrations.AlterField(
            model_name='games',
            name='game_description',
            field=django_quill.fields.QuillField(),
        ),
    ]
