# Generated by Django 3.2.5 on 2022-02-09 07:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='giveawayregistration',
            name='player',
        ),
        migrations.AddField(
            model_name='giveawayregistration',
            name='player',
            field=models.ManyToManyField(to='giveaways.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
