# Generated by Django 3.2.5 on 2022-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0004_giveaway_result_announcement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='giveawayregistration',
            name='set_winner',
            field=models.BooleanField(blank='False', default=False, null='False'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='player',
            name='address',
            field=models.TextField(blank='False', null='False'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='giveaway',
            name='result_announcement_date',
            field=models.DateTimeField(null=True),
        ),
    ]
