# Generated by Django 3.2.5 on 2022-02-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0005_auto_20220225_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giveawayregistration',
            old_name='giveaway_id',
            new_name='giveaway',
        ),
    ]
