# Generated by Django 3.2.5 on 2022-03-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0006_rename_giveaway_id_giveawayregistration_giveaway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giveawayregistration',
            name='set_winner',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giveawayregistration',
            name='winner',
            field=models.BooleanField(blank='False', default=False, null='False'),
            preserve_default='False',
        ),
        migrations.AlterUniqueTogether(
            name='winners',
            unique_together={('giveaway', 'winner')},
        ),
        migrations.DeleteModel(
            name='VideoGiveAway',
        ),
    ]
