# Generated by Django 3.2.5 on 2022-02-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0006_rename_giveaway_id_giveawayregistration_giveaway'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giveawayregistration',
            old_name='set_winner',
            new_name='winner',
        ),
    ]
